[package]
name = "scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
eframe = "0.31"
jwalk = "0.8"
rfd = "0.15"
trash = "5.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Ioctl",
] }
